services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: ["serve"]

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    entrypoint: ["/bin/sh", "-lc"]
    command: >
      "ollama pull phi3:mini &&
       ollama pull nomic-embed-text"
    restart: "no"

  app:
    build: .
    container_name: rag-agent
    depends_on:
      ollama:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully
    environment:
      DEBUG: "0"
      LOG_JSON: "1"
      MODEL_PROVIDER: ollama
      MODEL_NAME: phi3:mini
      OLLAMA_HOST: http://ollama:11434
      EMBEDDING_PROVIDER: ollama
      EMBEDDING_MODEL: nomic-embed-text
      EMBEDDING_METRIC: cosine
      EMBEDDING_CONCURRENCY: "6"
      MINIMAL_MODE: "false"
    ports:
      - "7860:7860"

volumes:
  ollama-models:
  chroma-data:
